# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
  commands:
    - pip install --upgrade pip
    - pip install -e '.[docs]'
    # Make sure RTD can find the html output
    - sphinx-build -b html docs $READTHEDOCS_OUTPUT/html
